spring.application.name=blog

jwt.secret=your-246-bit-secret-key-goes-here-change-this-to-a-secure-key
# database connection
spring.datasource.url=jdbc:postgresql://localhost:5433/blog
spring.datasource.username=user
spring.datasource.password=password

# hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect